name: "Gitea Mirror"

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      #- uses: actions/checkout@v2
      - uses: varunsridharan/action-gitea-mirror@main
        name: "Trigger Mirror"
        with:
          gh_username: ${{ secrets.GH_USERNAME }}
          accesstoken: ${{ secrets.GH_TOKEN }}
          gitea_host: ${{ secrets.GITEA_HOST }}
          gitea_username: ${{ secrets.GITEA_USERNAME }}
          gitea_accesstoken: ${{ secrets.GITEA_TOKEN }}
          gitea_gist_prefix: "gist"
          gitea_gist_surfix: ""
          gistsSource: true
          gistsStared: false
          repositoryStared: false
          repositorySource: false
          repositoryForked: false
