name: " ⏳  Stared Gists Mirror"

on:
  workflow_dispatch:

  schedule:
    - cron: '0 * * * *'

  push:

    paths:
      - .github/workflows/source-gists.yml

    branches:
      - main

jobs:
  mirror:
    name: "⏳  Mirror"
    runs-on: ubuntu-latest
    steps:
      - uses: varunsridharan/action-gitea-mirror@main
        name: "RUN"
        with:
          gh_username: ${{ secrets.GH_USERNAME }}
          gh_accesstoken: ${{ secrets.GH_TOKEN }}
          gitea_host: ${{ secrets.GITEA_HOST }}
          gitea_username: ${{ secrets.GITEA_USERNAME }}
          gitea_accesstoken: ${{ secrets.GITEA_TOKEN }}
          gitea_gist_prefix: "gist"
          gitea_gist_surfix: ""
          gistsSource: false
          gistsStared: true
          repositoryStared: false
          repositorySource: false
          repositoryForked: false
